### ISSUE TITLE
Gridlines in the rainbow chart

### ISSUE THREAD

**Issue by vaideeshl** [moonmath/static#1]
Hey mate! When you were posting the chart on imgur and reddit, the (horizontal) gridlines in the background were helpful. I liked how some gridlines were bolder than the others.
It'll be helpful if you can restore the horizontal gridlines, and possibly add vertical gridlines too!

**Comment by moonmath** [comment]
Thanks for opening the first issue!

I agree, grid lines are needed. Squeaky wheel gets the grease. Tackling this one first. 

May you be an example for all those who come after you.

**Comment by moonmath** [comment]
Check it out. You've got gridlines!

**Comment by vaideeshl** [comment]
Looks awesome mate! Cheers!
